version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 101010
      MYSQL_DATABASE: animated_portfolio
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  nextjs:
    build: .
    container_name: nextjs
    ports:
      - "3000:3000"
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASS: 101010
      DB_NAME: animated_portfolio
    depends_on:
      - db

volumes:
  mysql_data:
